version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - bimm_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bimm-backend-challenge
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - ALL_MAKES_ENDPOINT=${ALL_MAKES_ENDPOINT}
      - ALL_VEHICLE_TYPES_ENDPOINT=${ALL_VEHICLE_TYPES_ENDPOINT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src
    networks:
      - bimm_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - bimm_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    expose:
      - '6379'
    networks:
      - bimm_network

networks:
  bimm_network:
    name: bimm_network